set(SOURCE_LIST
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/BitmapAccess.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/ColorLookup.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/ConversionRGBA16.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/ConversionRGBAF.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/FreeImage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/FreeImageC.c
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/FreeImageIO.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/GetType.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/LFPQuantizer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/MemoryIO.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PixelAccess.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/J2KHelper.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/MNGHelper.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/Plugin.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginBMP.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginCUT.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginDDS.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginEXR.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginG3.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginGIF.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginHDR.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginICO.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginIFF.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginJ2K.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginJNG.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginJP2.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginJPEG.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginJXR.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginKOALA.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginMNG.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginPCD.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginPCX.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginPFM.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginPICT.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginPNG.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginPNM.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginPSD.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginRAS.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginRAW.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginSGI.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginTARGA.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginTIFF.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginWBMP.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginWebP.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginXBM.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PluginXPM.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/PSDParser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/TIFFLogLuv.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/Conversion.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/Conversion16_555.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/Conversion16_565.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/Conversion24.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/Conversion32.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/Conversion4.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/Conversion8.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/ConversionFloat.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/ConversionRGB16.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/ConversionRGBF.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/ConversionType.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/ConversionUINT16.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/Halftoning.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/tmoColorConvert.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/tmoDrago03.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/tmoFattal02.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/tmoReinhard05.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/ToneMapping.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/NNQuantizer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/WuQuantizer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/CacheFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/MultiPage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage/ZLibInterface.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Metadata/Exif.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Metadata/FIRational.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Metadata/FreeImageTag.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Metadata/IPTC.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Metadata/TagConversion.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Metadata/TagLib.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/Metadata/XTIFF.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImageToolkit/Background.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImageToolkit/BSplineRotate.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImageToolkit/Channels.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImageToolkit/ClassicRotate.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImageToolkit/Colors.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImageToolkit/CopyPaste.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImageToolkit/Display.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImageToolkit/Flip.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImageToolkit/JPEGTransform.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImageToolkit/MultigridPoissonSolver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImageToolkit/Rescale.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/FreeImageToolkit/Resize.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jaricom.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jcapimin.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jcapistd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jcarith.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jccoefct.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jccolor.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jcdctmgr.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jchuff.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jcinit.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jcmainct.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jcmarker.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jcmaster.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jcomapi.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jcparam.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jcprepct.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jcsample.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jctrans.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdapimin.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdapistd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdarith.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdatadst.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdatasrc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdcoefct.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdcolor.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jddctmgr.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdhuff.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdinput.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdmainct.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdmarker.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdmaster.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdmerge.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdpostct.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdsample.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jdtrans.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jerror.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jfdctflt.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jfdctfst.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jfdctint.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jidctflt.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jidctfst.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jidctint.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jmemmgr.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jmemnobs.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jquant1.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jquant2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/jutils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJPEG/transupp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibPNG/png.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibPNG/pngerror.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibPNG/pngget.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibPNG/pngmem.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibPNG/pngpread.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibPNG/pngread.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibPNG/pngrio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibPNG/pngrtran.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibPNG/pngrutil.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibPNG/pngset.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibPNG/pngtrans.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibPNG/pngwio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibPNG/pngwrite.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibPNG/pngwtran.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibPNG/pngwutil.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_aux.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_close.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_codec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_color.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_compress.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_dir.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_dirinfo.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_dirread.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_dirwrite.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_dumpmode.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_error.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_extension.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_fax3.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_fax3sm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_flush.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_getimage.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_jpeg.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_luv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_lzma.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_lzw.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_next.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_ojpeg.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_open.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_packbits.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_pixarlog.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_predict.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_print.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_read.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_strip.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_swab.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_thunder.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_tile.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_version.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_warning.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_write.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibTIFF4/tif_zip.c
    ${CMAKE_CURRENT_SOURCE_DIR}/ZLib/adler32.c
    ${CMAKE_CURRENT_SOURCE_DIR}/ZLib/compress.c
    ${CMAKE_CURRENT_SOURCE_DIR}/ZLib/crc32.c
    ${CMAKE_CURRENT_SOURCE_DIR}/ZLib/deflate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/ZLib/gzclose.c
    ${CMAKE_CURRENT_SOURCE_DIR}/ZLib/gzlib.c
    ${CMAKE_CURRENT_SOURCE_DIR}/ZLib/gzread.c
    ${CMAKE_CURRENT_SOURCE_DIR}/ZLib/gzwrite.c
    ${CMAKE_CURRENT_SOURCE_DIR}/ZLib/infback.c
    ${CMAKE_CURRENT_SOURCE_DIR}/ZLib/inffast.c
    ${CMAKE_CURRENT_SOURCE_DIR}/ZLib/inflate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/ZLib/inftrees.c
    ${CMAKE_CURRENT_SOURCE_DIR}/ZLib/trees.c
    ${CMAKE_CURRENT_SOURCE_DIR}/ZLib/uncompr.c
    ${CMAKE_CURRENT_SOURCE_DIR}/ZLib/zutil.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/bio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/cio.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/dwt.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/event.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/function_list.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/image.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/invert.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/j2k.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/jp2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/mct.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/mqc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/openjpeg.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/opj_clock.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/pi.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/raw.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/t1.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/t2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/tcd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibOpenJPEG/tgt.c
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IexMath/IexMathFpu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/b44ExpLogTable.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfAcesFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfB44Compressor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfBoxAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfChannelList.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfChannelListAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfChromaticities.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfChromaticitiesAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfCompositeDeepScanLine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfCompressionAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfCompressor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfConvert.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfCRgbaFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfDeepCompositing.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfDeepFrameBuffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfDeepImageStateAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfDeepScanLineInputFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfDeepScanLineInputPart.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfDeepScanLineOutputFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfDeepScanLineOutputPart.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfDeepTiledInputFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfDeepTiledInputPart.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfDeepTiledOutputFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfDeepTiledOutputPart.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfDoubleAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfDwaCompressor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfEnvmap.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfEnvmapAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfFastHuf.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfFloatAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfFloatVectorAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfFrameBuffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfFramesPerSecond.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfGenericInputFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfGenericOutputFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfHeader.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfHuf.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfInputFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfInputPart.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfInputPartData.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfIntAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfIO.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfKeyCode.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfKeyCodeAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfLineOrderAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfLut.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfMatrixAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfMisc.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfMultiPartInputFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfMultiPartOutputFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfMultiView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfOpaqueAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfOutputFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfOutputPart.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfOutputPartData.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfPartType.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfPizCompressor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfPreviewImage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfPreviewImageAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfPxr24Compressor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfRational.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfRationalAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfRgbaFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfRgbaYca.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfRle.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfRleCompressor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfScanLineInputFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfStandardAttributes.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfStdIO.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfStringAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfStringVectorAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfSystemSpecific.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfTestFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfThreading.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfTileDescriptionAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfTiledInputFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfTiledInputPart.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfTiledMisc.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfTiledOutputFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfTiledOutputPart.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfTiledRgbaFile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfTileOffsets.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfTimeCode.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfTimeCodeAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfVecAttribute.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfVersion.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfWav.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfZip.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmImf/ImfZipCompressor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/Imath/ImathBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/Imath/ImathColorAlgo.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/Imath/ImathFun.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/Imath/ImathMatrixAlgo.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/Imath/ImathRandom.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/Imath/ImathShear.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/Imath/ImathVec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/Iex/IexBaseExc.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/Iex/IexThrowErrnoExc.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/Half/half.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmThread/IlmThread.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmThread/IlmThreadMutex.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmThread/IlmThreadPool.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IlmThread/IlmThreadSemaphore.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/OpenEXR/IexMath/IexMathFloatExc.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/LibRawLite/internal/dcraw_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/LibRawLite/internal/dcraw_fileio.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/LibRawLite/internal/demosaic_packs.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/LibRawLite/src/libraw_c_api.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/LibRawLite/src/libraw_cxx.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/LibRawLite/src/libraw_datastream.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dec/alpha_dec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dec/buffer_dec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dec/frame_dec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dec/idec_dec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dec/io_dec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dec/quant_dec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dec/tree_dec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dec/vp8l_dec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dec/vp8_dec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dec/webp_dec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/demux/anim_decode.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/demux/demux.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/alpha_processing.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/alpha_processing_mips_dsp_r2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/alpha_processing_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/alpha_processing_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/alpha_processing_sse41.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/cost.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/cost_mips32.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/cost_mips_dsp_r2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/cost_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/cpu.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/dec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/dec_clip_tables.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/dec_mips32.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/dec_mips_dsp_r2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/dec_msa.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/dec_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/dec_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/dec_sse41.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/enc_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/enc_mips32.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/enc_mips_dsp_r2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/enc_msa.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/enc_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/enc_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/enc_sse41.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/filters.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/filters_mips_dsp_r2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/filters_msa.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/filters_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/filters_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/lossless.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/lossless_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/lossless_enc_mips32.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/lossless_enc_mips_dsp_r2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/lossless_enc_msa.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/lossless_enc_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/lossless_enc_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/lossless_enc_sse41.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/lossless_mips_dsp_r2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/lossless_msa.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/lossless_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/lossless_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/rescaler.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/rescaler_mips32.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/rescaler_mips_dsp_r2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/rescaler_msa.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/rescaler_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/rescaler_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/ssim.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/ssim_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/upsampling.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/upsampling_mips_dsp_r2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/upsampling_msa.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/upsampling_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/upsampling_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/upsampling_sse41.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/yuv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/yuv_mips32.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/yuv_mips_dsp_r2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/yuv_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/yuv_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/dsp/yuv_sse41.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/alpha_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/analysis_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/backward_references_cost_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/backward_references_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/config_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/cost_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/filter_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/frame_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/histogram_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/iterator_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/near_lossless_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/picture_csp_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/picture_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/picture_psnr_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/picture_rescale_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/picture_tools_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/predictor_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/quant_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/syntax_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/token_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/tree_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/vp8l_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/enc/webp_enc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/mux/anim_encode.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/mux/muxedit.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/mux/muxinternal.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/mux/muxread.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/utils/bit_reader_utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/utils/bit_writer_utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/utils/color_cache_utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/utils/filters_utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/utils/huffman_encode_utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/utils/huffman_utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/utils/quant_levels_dec_utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/utils/quant_levels_utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/utils/random_utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/utils/rescaler_utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/utils/thread_utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibWebP/src/utils/utils.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/decode/decode.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/decode/JXRTranscode.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/decode/postprocess.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/decode/segdec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/decode/strdec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/decode/strdec_x86.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/decode/strInvTransform.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/decode/strPredQuantDec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/encode/encode.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/encode/segenc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/encode/strenc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/encode/strenc_x86.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/encode/strFwdTransform.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/encode/strPredQuantEnc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/sys/adapthuff.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/sys/image.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/sys/strcodec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/sys/strPredQuant.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/image/sys/strTransform.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/jxrgluelib/JXRGlue.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/jxrgluelib/JXRGlueJxr.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/jxrgluelib/JXRGluePFC.c
    ${CMAKE_CURRENT_SOURCE_DIR}/LibJXR/jxrgluelib/JXRMeta.c
)
